### ISSUE TITLE
phone number input should follow format

### ISSUE THREAD

**Issue by csell5** [HelloUnspecified/unspecified.io#36] opened 2020-04-16 14:38 UTC
![image](https://user-images.githubusercontent.com/772569/79469537-ebd34d80-7fc5-11ea-8d83-1aaf3135a8ab.png)

but get 

![image](https://user-images.githubusercontent.com/772569/79469595-fdb4f080-7fc5-11ea-81f8-c9e3ce3a1c8b.png)

**Comment by saragibby** [comment] 2020-04-17 22:40
closing this as a duplicate of #35

**Closed by saragibby** 2020-04-17 22:40 UTC
